- name: restart thehive
  service: name=thehive state=restarted
  notify: wait for the service to come up

- name: reload systemd
  shell: systemctl daemon-reload

- name: wait for the service to come up
  wait_for: port={{ thehive.http.port }} timeout=30
